#!/bin/sh

# New version that produces a single HTML file rather than one
# with <frame> elements, to overcome the fact that browsers treat
# different local files as cross-origin

# Users need to provide a key for the map provider (currently Mapbox), in the
# environment variable GEOPARSER_MAP_KEY

GEOPARSER_MAP_KEY="${GEOPARSER_MAP_KEY:-unset}"

usage="gazmap [-top] nertagged-file gaz-file"
descr="Display locations on a map"

. `dirname $0`/setup
lib=$here/lib/georesolve

toponly=false
if [ $1 = "-top" ]; then
  shift
  toponly=true
fi

if [ $# -ne 2 ]; then
  echo "usage: $usage" >&2
  exit 2
fi

nerfile="$1"
gazfile="$2"


# Create the list file (should we keep this?  if so do it in run instead)

lxt -s $lib/gazlist.xsl <"$gazfile" >$tmp-gazlist

# make a temporary copy of the nerfile to avoid problems with base uri in stylesheet

cp "$nerfile" $tmp-nerfile

lxt -s $lib/gazmap.xsl -p key "$GEOPARSER_MAP_KEY" -p toponly "$toponly" -p nerfile "$tmp-nerfile" -p listfile "$tmp-gazlist" <"$gazfile"
