# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: defoe-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x65\x66oe-service.proto\"p\n\rSubmitRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\nquery_name\x18\x03 \x01(\t\x12\x14\n\x0cquery_config\x18\x04 \x01(\t\x12\x15\n\rdata_endpoint\x18\x05 \x01(\t\"+\n\x0eSubmitResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1b\n\rStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\"`\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\x10\n\x08progress\x18\x04 \x01(\x03\x12\x0e\n\x06result\x18\x05 \x01(\t2g\n\x05\x44\x65\x66oe\x12.\n\tSubmitJob\x12\x0e.SubmitRequest\x1a\x0f.SubmitResponse\"\x00\x12.\n\tGetStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\"\x00\x62\x06proto3')



_SUBMITREQUEST = DESCRIPTOR.message_types_by_name['SubmitRequest']
_SUBMITRESPONSE = DESCRIPTOR.message_types_by_name['SubmitResponse']
_STATUSREQUEST = DESCRIPTOR.message_types_by_name['StatusRequest']
_STATUSRESPONSE = DESCRIPTOR.message_types_by_name['StatusResponse']
SubmitRequest = _reflection.GeneratedProtocolMessageType('SubmitRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITREQUEST,
  '__module__' : 'defoe_service_pb2'
  # @@protoc_insertion_point(class_scope:SubmitRequest)
  })
_sym_db.RegisterMessage(SubmitRequest)

SubmitResponse = _reflection.GeneratedProtocolMessageType('SubmitResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITRESPONSE,
  '__module__' : 'defoe_service_pb2'
  # @@protoc_insertion_point(class_scope:SubmitResponse)
  })
_sym_db.RegisterMessage(SubmitResponse)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREQUEST,
  '__module__' : 'defoe_service_pb2'
  # @@protoc_insertion_point(class_scope:StatusRequest)
  })
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'defoe_service_pb2'
  # @@protoc_insertion_point(class_scope:StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

_DEFOE = DESCRIPTOR.services_by_name['Defoe']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBMITREQUEST._serialized_start=23
  _SUBMITREQUEST._serialized_end=135
  _SUBMITRESPONSE._serialized_start=137
  _SUBMITRESPONSE._serialized_end=180
  _STATUSREQUEST._serialized_start=182
  _STATUSREQUEST._serialized_end=209
  _STATUSRESPONSE._serialized_start=211
  _STATUSRESPONSE._serialized_end=307
  _DEFOE._serialized_start=309
  _DEFOE._serialized_end=412
# @@protoc_insertion_point(module_scope)
